# Generated by Django 5.2.1 on 2025-05-27 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_problem', '0001_initial'),
        ('home', '0004_testcase_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.problem'),
        ),
    ]
