# Generated by Django 5.2.1 on 2025-05-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_problem', '0002_codesubmission_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesubmission',
            name='problem',
        ),
    ]
