# Generated by Django 5.2.1 on 2025-05-28 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_problem', '0003_remove_codesubmission_problem'),
        ('home', '0008_problem_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.problem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='verdict',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.problem')),
            ],
        ),
    ]
