# Generated by Django 5.2.1 on 2025-05-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(default=True),
        ),
    ]
