# Generated by Django 5.2.1 on 2025-05-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testcase_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='is_hidden',
        ),
    ]
