# Generated by Django 5.2.1 on 2025-05-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_testcase_is_hidden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
